# config/config.yaml
data:
  s3_bucket: 'nfl-data-bucket'
  s3_key: 'nfl_games_2020_2021.csv'

model:
  type: 'RandomForestClassifier'
  params:
    n_estimators: 100
    max_depth: 10
    random_state: 42

training:
  test_size: 0.2
  random_state: 42

sagemaker:
  instance_type: 'ml.m5.large'
  instance_count: 1

visualization:
  feature_importance_top_n: 10
